// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoService.DataAccess;

#nullable disable

namespace RepoService.DataAccess.Migrations
{
    [DbContext(typeof(RepoDbContext))]
    partial class RepoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoService.Models.ProductModel", b =>
                {
                    b.Property<Guid>("PackageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ARPCONTACT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARPHELPLINK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARPHELPTELEPHONE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARPURLINFOABOUT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARPURLUPDATEINFO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsX64")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductCode")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UpgradeCode")
                        .HasColumnType("uuid");

                    b.HasKey("PackageCode");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
